import Head from "next/head";
import GlobalStyle from "../util/globalStyles";
import Navbar from "../components/NavBar/Navbar";
import VideoPlayer from "../components/VideoPlayer/VideoPlayer";
import CTATiles from "../components/CTATIles/CTATiles";
import MemberTestimonials from "../components/MemberTestimonials/MemberTestimonials";
import VideoSelection from "../components/VideoSelection/VideoSelection";
import CoverCarousel from "../components/CoverCarousel/CoverCarousel";
import Footer from "../components/Footer/Footer";

import navBarData from "../components/NavBar/data/model";
import CTATilesData from "../components/CTATIles/data/model";
import memberTestimonialsData from "../components/MemberTestimonials/data/model";
import videoSelectionData from "../components/VideoSelection/data/model";
import coversData from "../components/CoverCarousel/data/model";
import footerData from "../components/Footer/data/model";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle />
      <Navbar {...navBarData} />
      <VideoPlayer />
      <CTATiles {...CTATilesData} />
      <MemberTestimonials {...memberTestimonialsData} />
      <VideoSelection {...videoSelectionData} />
      <CoverCarousel {...coversData} />
      <Footer {...footerData} />
    </>
  );
}
