import Head from 'next/head'
import Navbar from '../components/NavBar/Navbar';
import VideoPlayer from '../components/VideoPlayer/VideoPlayer';
import navBarData from '../components/NavBar/data/model';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar {...navBarData} />
      <VideoPlayer />
    </>
  );
}
